services:
  aibpmn:
    image: msgcg/aibpmn:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aibpmn
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0,*
      - SQLITE_DB_PATH=/app/data/db.sqlite3
    volumes:
      - aibpmn_data:/app/data
      - ./knowledge_base:/app/knowledge_base

volumes:
  aibpmn_data:
