# Generated by Django 6.1.1 on 2026-09-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название диаграммы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Исходное описание процесса')),
                ('dsl_code', models.TextField(blank=True, default='', verbose_name='Код BPMN-as-Code (DSL)')),
                ('bpmn_xml', models.TextField(blank=True, default='', verbose_name='BPMN 2.0 XML')),
                ('svg_preview', models.TextField(blank=True, default='', verbose_name='SVG миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Диаграмма',
                'verbose_name_plural': 'Диаграммы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'GigaChat Архитектор'), ('system', 'Системное сообщение')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('dsl_code', models.TextField(blank=True, default='', verbose_name='Сгенерированный DSL код')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Архитектурное пояснение')),
                ('is_error', models.BooleanField(default=False, verbose_name='Ошибка генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='architect.diagram', verbose_name='Диаграмма')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='diagram',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='architect.project', verbose_name='Проект'),
        ),
    ]
