# Generated by Django 6.1.1 on 2026-10-03 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architect', '0003_default_root_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGigaChatCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.TextField(blank=True, default='', verbose_name='Авторизационный ключ GigaChat (Base64)')),
                ('scope', models.CharField(default='GIGACHAT_API_PERS', max_length=64, verbose_name='Scope API')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gigachat_credential', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключ GigaChat пользователя',
                'verbose_name_plural': 'Ключи GigaChat пользователей',
                'ordering': ['-updated_at'],
            },
        ),
    ]
